services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: inventory
      # this is not secure, but we'll keep it for now as it's a demo project
      POSTGRES_USER: ferovinum
      POSTGRES_PASSWORD: ferovinum
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/init_db.sql # inits the sample DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ferovinum"]
      interval: 5s
      timeout: 5s
      retries: 5

  inventory:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: inventory
      DB_USER: ferovinum
      DB_PASSWORD: ferovinum

volumes:
  postgres-data:
